### ISSUE TITLE
Create a hexSticker for the package

### ISSUE THREAD

**Issue by swsoyee** [swsoyee/r3dmol#14]
I don't have much sense about LOGO design, do you have any idea about this topic? @BradyAJohnston

**Comment by BradyAJohnston** [comment]
Put together an initial sketch. Thoughts on layout / font / colours?

![final_colours](https://user-images.githubusercontent.com/36021261/108641673-9bd1eb00-74f4-11eb-89b7-231938be29fc.png)

**Comment by swsoyee** [comment]
@BradyAJohnston Great work! Did you created the logo by using https://github.com/GuangchuangYu/hexSticker ?

It would be better if the process of creating a logo is reproducible.

**Comment by BradyAJohnston** [comment]
I have recreated it in the following: 
```r
library(hexSticker)
library(showtext)

font_add_google("Courier Prime", "courier")

sticker(
  subplot = "inst/logo/cartoon.png",
  package = "r3dmol",
  s_x = 1.05,
  s_y = 0.8,
  s_width = 1,
  s_height = 1,
  dpi = 600,
  p_family = "courier",
  p_size = 6,
  filename = "inst/logo/logo.png",
  p_color = "gray5",
  h_color = "gray20",
  h_fill = "#6CCBFA"
)
```

![logo](https://user-images.githubusercontent.com/36021261/108662426-6643f680-7522-11eb-869c-db4f0298cfe7.png)

**Comment by swsoyee** [comment]
Emmm, it seems that the resolution of cartoon image is not as good as the previous one. Anyway, Would you might to create a Pull Request to add the high resolution cartoon image to `/man/figures/cartoon.png`? I will try to turn the logo and create a favicon to pkgdown site.

**Comment by BradyAJohnston** [comment]
Yeah I'm unsure how to fix it. I'm basically using the same image, but when being parsed through the `{hexSticker}` pipeline, it seems to pixelate it for some reason. I've tried with using `{magick}` as well. Seems that the rendering done by R might degrade the image quality somewhat when dealing with the raster.

I'm going to try and find another workaround to get things looking smooth. I'll set up the PR though for the cartoon.
