### ISSUE TITLE
m_add_lines()

### ISSUE THREAD

**Issue by BradyAJohnston** [swsoyee/r3dmol#15]
Support for creating multiple lines at once. 

Currently, the `m_add_line()` will only create a single line from the two given points in space. Ideally I would like to be able to feed a vector / list of points into the `start` and `end` arguments, and it will create multiple lines. 

I've tried playing around with looping over the `m_add_line()` multiple times, but it doesn't work properly. I don't know enough about the javascript side of things as to why it's not working, but would appreciate ideas as to how to get it to work. 

Potential also for applying to `m_add_cylinder()`, `m_add_sphere()` etc

**Comment by swsoyee** [comment]
I haven't did enough search and try, but it might be work if create `m_add_lins()` and pass the args to `m_add_line` inside?

**Comment by swsoyee** [comment]
I have pushed a commit about the implementation of `m_add_lines()`. Other `m_add_*()` should be able to be implemented in the same way.

**Comment by swsoyee** [comment]
A better solution:

1. change `m_add_line()` to an internal funtion and rename it to `.m_add_line()` or something better;
2. rename `m_add_lines()` to `m_add_line()`.
3. create a new funtion to create `LineSpec` list.
4. If the `line_specs` is a list only contains 1 `LineSpec` element, it will create only a line. If the `line_specs` contains multiple `LineSpec` elements. In this way, we don't need two functions named `m_add_line()` and `m_add_lines()` with different usage, it will be more simple to understand for maintainer and easy to use for user.
