### ISSUE TITLE
Addition of Interactive Buttons

### ISSUE THREAD

**Issue by BradyAJohnston** [swsoyee/r3dmol#23]
Unsure how it would be implemented, but enabling the creation of buttons through functions that would resemble like that below (on the [docs page](http://3dmol.csb.pitt.edu/doc/index.html):
<p align="center">
<img src="https://user-images.githubusercontent.com/36021261/110227313-ffbfcf00-7f4a-11eb-84c1-5a30e12ee1b6.png" width="400"></P>

I'm not wanting the complete functionality of `{r3dmol}` exposed in button form, but maybe enabling the creation of a button that could switch between cartoon or stick representation would good. 

I am unsure if it is possible to implement this or not. I had an attempt and was unable to get it working, so your expertise would be appreciated.

**Comment by swsoyee** [comment]
I think it should be possible, this needs some enhancement on the JavaScript side. Since I also have no relevant experience before, the implementation is predicted to take 15 to 20 hours of work.
