### ISSUE TITLE
Layout Support

### ISSUE THREAD

**Issue by BradyAJohnston** [swsoyee/r3dmol#24]
Enable multiple-viewer formatting like that demonstrated in the `3Dmol.js` docs.

<p align="center">
<img src="https://user-images.githubusercontent.com/36021261/110227384-0bf85c00-7f4c-11eb-93ad-d3b0ab325ac7.png" width="600px">
</p>

Again I tried having a go but don't know enough about javascript to have any success. Any advice would be appreciated.

**Comment by swsoyee** [comment]
Due to the lack of understanding of the documentation as a whole during the initial development of the project, it was difficult to extend this part and required refactoring of the existing viewer initialization part in JavaScript side. The estimated development time is more than 20 hours.
