### ISSUE TITLE
Next Official Release

### ISSUE THREAD

**Issue by BradyAJohnston** [swsoyee/r3dmol#28]
When do we want to push the next official release to CRAN? What sort of roadmap? Should it b1 0.1.2 or 0.2? We've added a lot of great features and I'd love to get it out to CRAN for people to use 😄

**Comment by swsoyee** [comment]
I have submitted it yesterday, v0.1.2 it's under review now 😉

**Comment by BradyAJohnston** [comment]
This is excellent news! Thanks :)

**Comment by swsoyee** [comment]
@BradyAJohnston Help wanted.
From CRAN comment:

> Thanks, we see:
>
> Size of tarball: 9808759 bytes
>
> Not more than 5 MB foer a CRAN package, please.

For example, I add a example `cube_benzene_homo` data for showing how to use `m_add_isosurface`: https://swsoyee.github.io/r3dmol/reference/m_add_isosurface.html

But the size of dataset is too large so it will increase the package size.
Could you help me to alternative datasets (a PR is perfer) to handle this problem?

The main PDB file https://swsoyee.github.io/r3dmol/reference/pdb_6zsl.html we using in the package for examples is also a little bit large. It may be necessary to find a more suitable size of PDB for our exmaples (another PR is perfer).

There may be slightly more work to be done, and `v0.1.2` will have to be released later.

**Comment by BradyAJohnston** [comment]
Yep I can look into changing up datasets to reduce size. I am currently moving house (moving across the country) so the next week or so I may or may not be able to do some work on it (limited access to computer).

**Comment by swsoyee** [comment]
I need to apologize, I forgot to remove some unnecessary files during building, now the package size has been completely reduced to meet the specifications, resubmit v0.1.2.

**Comment by BradyAJohnston** [comment]
No worries! Will wait to see what CRAN review says. :)

**Comment by swsoyee** [comment]
> Dear maintainer,
> 
> thanks, package r3dmol_0.1.2.tar.gz is on its way to CRAN.
> 
> Best regards,
