### ISSUE TITLE
predicted 3D structures in *pdb format

### ISSUE THREAD

**Issue by Tsingsjeen** [swsoyee/r3dmol#32]
I predicted the 3D structure of my protein, I am wondering whether I can input the generated pdb data?

**Comment by BradyAJohnston** [comment]
Hi there! Thanks for commenting. If your predicted structure is a `.pdb` file, then yes you can import it. 

Just use the path to your file when you create the viewer like below: 

```r
r3dmol() %>% 
  m_add_model("path/to/file.pdb", format = "pdb") %>% 
  m_zoom_to()

```

Give it a try and let me know how you go.

**Comment by Tsingsjeen** [comment]
excellent, cannot wait to try!

Great thanks!

**Comment by BradyAJohnston** [comment]
Please do get in contact if you have further questions or if you run into any problems!
