### ISSUE TITLE
Bump 3Dmol.js version to 1.7

### ISSUE THREAD

**Issue by swsoyee** [swsoyee/r3dmol#41]
https://github.com/3dmol/3Dmol.js/releases/tag/1.7.0
If anyone can help it would be greatly appreciated.

**Comment by BradyAJohnston** [comment]
Can do! The ability to provide coordinates as an array should speed up loading times from `{bio3d}` objects as well.

**Comment by swsoyee** [comment]
@BradyAJohnston Hi, I have update 3Dmol.js to the latest version. You could add `screenOffset` now (https://github.com/swsoyee/r3dmol/pull/38#discussion_r697579222).
