### ISSUE TITLE
Color by b-factor (spectrum)

### ISSUE THREAD

**Issue by dschust-r** [swsoyee/r3dmol#45]
Thank you for the great package, it's really nice to use and makes protein vis in R easy!

I was wondering if maybe you know a way to color structures by b-factor using r3dmol? I've been checking 3dmol but I don't think they have implemented that functionality yet. 
Unfortunately, I don't know any javascript and I am guessing this would have to be used as a colorfunction in the `m_style_cartoon()` function. 

Do you maybe have any suggestions for this?

**Comment by dschust-r** [comment]
Thank you for the reply, that's not quite what I meant. Sorry, I should have clarified. The b-factor is a continuous number, assigned to each position. So you would have different colors on different regions.

**Comment by BradyAJohnston** [comment]
I hadn't thought to look into colouring by b-factor, but you are right that the support for it isn't obvious in `3Dmol.js`. 

I have had a play around, and it's possible! We don't have a dedicated function for it (but can certainly make one) but you can pass a list to anything that has the `colorScheme` argument (such as `m_style_surface()` and `m_style_ballnstick()`).

```r
r3dmol() %>% 
  m_add_model(data = pdb_1j72) %>% 
  m_add_surface(
    type = "SAS",
    style = m_style_surface(
      colorScheme = list(prop = "b", gradient = "roygb", min = 10, max = 200)
    )
  ) %>%
  m_zoom_to()
```
![image](https://user-images.githubusercontent.com/36021261/158394714-20790cb1-aee2-4500-8c90-7449272eadc9.png)

```r
r3dmol() %>% 
  m_add_model(data = pdb_1j72) %>% 
  m_add_style(
    m_style_ballnstick(
      colorScheme = list(prop = "b", gradient = "roygb", min = 10, max = 200)
    )
  ) %>% 
  m_zoom_to()
```
![image](https://user-images.githubusercontent.com/36021261/158394778-6017c3c7-e363-4d57-8385-374da4751e4b.png)


In these examples, I am using one of the pre-defined colorschemes that already exist within `3Dmol.js`, though they aren't well documented. 
![image](https://user-images.githubusercontent.com/36021261/158395026-5b34a065-83cb-4858-aa8c-5f5e6e420218.png)

I'm sure we could probably implement user-defined gradients a bit better, but @swsoyee would know more about the javascript side of that than I would (I'm the structural biologist, he's the proper javascript developer).

I don't quite know how to implement the gradients for the cartoon representations, I am showing an example below, but @swsoyee will need to help us out with being able to define a gradient inside of the function.

```r
r3dmol() %>%
  m_add_model(data = pdb_1j72) %>%
  m_set_style(style = m_style_cartoon(
    colorfunc = "
        function(atom) {
          return atom.b < 80 ? 'red' : 'white';
        }"
  )) %>%
  m_zoom_to()
```
![image](https://user-images.githubusercontent.com/36021261/158395752-ec89a660-4b1b-40d9-8937-01f2fc6f646a.png)

**Comment by BradyAJohnston** [comment]
For clarification as well @swsoyee, for the cartoon javascript function, the b-factors would range from `0` to `100` and we would like to select a colour from a vector based on that. I know how I would do it in `R`, 

```r
colour_gradient_vector[round(protein$b)]
```

But I don't know an easy way to define a vector of hex codes or something similar in javascript.

**Comment by dschust-r** [comment]
@BradyAJohnston thank you so much! That already helps a lot. 

I think the b-factors can even go higher than 100 for "real" structures. For AF predictions they go from 0-100 - as far as I know.

**Comment by swsoyee** [comment]
@BradyAJohnston Thank you for your detailed additions!

@dschust-r You could set color for each atom like this:

```r
# Set color for each atom
color_vector <- paste0(c(rep('"blue"', 30), rep('"red"', 20), rep('"white"', 40), rep('"yellow"', 10)), collapse = ",")

r3dmol() %>%
  m_add_model(data = pdb_1j72) %>%
  m_set_style(style = m_style_cartoon(
    colorfunc = paste0("
        function(atom) {
          const color = [", color_vector, "];
          return color[atom.resi];
        }"
  ))) %>%
  m_zoom_to() %>%
  m_png()

```

![image](https://user-images.githubusercontent.com/20528423/158399036-51b687e2-0e7d-4a91-ae78-ac26008c0bcd.png)

Or, If you know the what props are in atom, you could do this directly through Javascript functions

```r
r3dmol() %>%
  m_add_model(data = pdb_1j72) %>%
  m_set_style(style = m_style_cartoon(
    colorfunc = "
        function(atom) {
          if (atom.b < 50) {return 'red'};
          if (atom.b < 80 && atom.b >= 50) {return 'green'};
          return 'white';
        }"
  )) %>%
  m_zoom_to() %>%
  m_png()
```

![image](https://user-images.githubusercontent.com/20528423/158400193-1d918ff8-6e67-47ec-bd1d-a203f3e23dec.png)

**Comment by BradyAJohnston** [comment]
Okay so it turns out that `colorscheme` is also supported for cartoons, but it isn't documented at all inside of `3Dmol.js` so we haven't explicitly added support for it inside of `m_style_cartoon()` function (yet!). 

The result of `m_style_cartoon()` however is just a list, so you can add in the `colorscheme` (all lowercase for the javascript-facing stuff) and define the gradient there as in the other examples: 

```r 
library(r3dmol)
cartoon_styles <- m_style_cartoon()
cartoon_styles$cartoon$colorscheme <- list(prop = "b", gradient = "roygb", min = 10, max = 200)

r3dmol() %>% 
  m_add_model(pdb_1j72) %>% 
  m_add_style(style = cartoon_styles) %>% 
  m_zoom_to()
```
![image](https://user-images.githubusercontent.com/36021261/158402369-deb2a98a-f374-4f1e-98cf-0396b8f86abc.png)

**Comment by dschust-r** [comment]
Thank you both @swsoyee and @BradyAJohnston that is really helpful and works like a charm for my data!

**Comment by BradyAJohnston** [comment]
Based on @swsoyee's response as well, you can define your own colour gradient in R as below, and use that in the `colorfunc` argument. 

```r
make_colours <- function(x, start = "red", end = "green") {
  colorfun <- colorRampPalette(c(start, end))
  
  paste0('"', paste(colorfun(x), collapse = '", "'), '"')
}


r3dmol() %>%
  m_add_model(data = pdb_1j72) %>%
  m_set_style(style = m_style_cartoon(
    colorfunc = paste0("
        function(atom) {
          const color = [", make_colours(120, "blue", "tomato"),"]
          return color[Math.round(atom.b)]
        }")
  )) %>%
  m_zoom_to()
```

![image](https://user-images.githubusercontent.com/36021261/158406073-982356ad-e529-49f9-800b-836f4c91686b.png)


Thanks for opening the issue, we'll be sure to add in proper support for the colour gradients :)

**Comment by dschust-r** [comment]
That's amazing! Thank you so much, works great 🥳 

So happy that it works!

**Comment by swsoyee** [comment]
It looks like this problem has been solved, so I'll close it for now. Feel free to reopen it again if needed.
