### ISSUE TITLE
How can I export this figure in the ShinyApp

### ISSUE THREAD

**Issue by chenxi199506** [swsoyee/r3dmol#49]
![image](https://user-images.githubusercontent.com/77444305/205501474-5e152368-6430-46ac-8e1f-44a13cf7bf4c.png)

p <- r3dmol(id = "demo_sdf", elementId = "demo_sdf") %>%
                        m_add_model(data = benz, format = "sdf") %>%
                        m_set_style(style = m_style_stick()) %>%
                        m_set_style(sel = m_sel(model = 0),
                                    style = m_style_stick(colorScheme = "cyanCarbon")) %>%
                        m_zoom_to()

 output$pic <- renderPlot({(p)}, res = 96)

I am using this R package for a new shiny app construction in my paper

I find when i render this picture, it only shows in the Rstudio Plot window instead of the web

How can i fix that problem?

Thank you so much !

Ps
 this was a great and very useful R package  for me ! Thanks again for this amazing work !

**Comment by swsoyee** [comment]
Actually, the output of r3dmol it's a web widget, so you can't export image natively.
Also see #48.

If you want to add output of r3dmol into Shiny,
you could use `renderR3dmol` https://github.com/swsoyee/r3dmol/blob/master/inst/example/app.R#L66
and `r3dmolOutput` https://github.com/swsoyee/r3dmol/blob/master/inst/example/app.R#L56.
And add [`m_png()`](https://swsoyee.github.io/r3dmol/reference/m_png.html) at the end of r3dmol object.

**Comment by chenxi199506** [comment]
Thank you so much for your reply!
It perfectly solved my problems!

I will cite your  R package in my paper and recommend it for more researchers !

What a talented work !
